[build]
command = "npm run build"
publish = "dist/apps/demo-monorepo/.next"
# ignore = "git diff --quiet $CACHED_COMMIT_REF $COMMIT_REF ../../"

[dev]
command = "npm run start"
targetPort = 4200

[[plugins]]
package = "../plugin-wrapper"

[build.environment]
# cache Cypress binary in local "node_modules" folder
# so Netlify caches it
CYPRESS_CACHE_FOLDER = "../node_modules/.CypressBinary"
# set TERM variable for terminal output
TERM = "xterm"
NODE_VERSION = "16.13.2"

[[plugins]]
package = "@netlify/plugin-local-install-core"
