[build]
command = "next build"
publish = ".next"
ignore = "git diff --quiet $CACHED_COMMIT_REF $COMMIT_REF . ../"

[build.environment]
# cache Cypress binary in local "node_modules" folder
# so Netlify caches it
CYPRESS_CACHE_FOLDER = "../node_modules/.CypressBinary"

[dev]
framework = "#static"

[[plugins]]
package = "./local-plugin"

[[plugins]]
package = "@netlify/plugin-local-install-core"

[[context.deploy-preview.plugins]]
package = "netlify-plugin-cypress"

[context.deploy-preview.plugins.inputs]
configFile = "../cypress/config/ci.json"

# [[redirects]]
# from = '/_next/image*'
# query = { url = ':url', w = ':width', q = ':quality' }
# to = '/.netlify/builders/_ipx/w_:width,q_:quality/:url'
# status = 200

# [[redirects]]
# from = "/*"
# to = "/.netlify/functions/___netlify-handler/:splat"
# status = 200
